pacman -S aalib
pacman -S abs
pacman -S accountsservice
pacman -S ack
pacman -S acl
pacman -S adwaita-icon-theme
pacman -S alsa-lib
pacman -S alsa-plugins
pacman -S ansible
pacman -S apache
pacman -S apr
pacman -S apr-util
pacman -S archlinux-keyring
pacman -S artwiz-fonts
pacman -S aspcud
pacman -S aspell
pacman -S aspell-en
pacman -S aspell-ru
pacman -S at-spi2-atk
pacman -S at-spi2-core
pacman -S atk
pacman -S atkmm
pacman -S atom-editor
pacman -S attr
pacman -S audiofile
pacman -S autoconf
pacman -S automake
pacman -S avahi
pacman -S babl
pacman -S baobab
pacman -S bash
pacman -S binutils
pacman -S bison
pacman -S blas
pacman -S blender
pacman -S bluez
pacman -S boost
pacman -S boost-libs
pacman -S brackets
pacman -S bridge-utils
pacman -S bzip2
pacman -S bzr
pacman -S ca-certificates
pacman -S ca-certificates-cacert
pacman -S ca-certificates-mozilla
pacman -S ca-certificates-utils
pacman -S cabextract
pacman -S cairo
pacman -S cairomm
pacman -S camlp4
pacman -S cantarell-fonts
pacman -S caribou
pacman -S cdparanoia
pacman -S celt
pacman -S cfitsio
pacman -S cheese
pacman -S chromaprint
pacman -S cifs-utils
pacman -S clasp
pacman -S clucene
pacman -S clutter
pacman -S clutter-gst
pacman -S clutter-gst2
pacman -S clutter-gtk
pacman -S cmake
pacman -S cogl
pacman -S coin
pacman -S colord
pacman -S colord-gtk
pacman -S compositeproto
pacman -S coreutils
pacman -S cppo
pacman -S cracklib
pacman -S cronie
pacman -S cryptsetup
pacman -S ctags
pacman -S cups-pk-helper
pacman -S curl
pacman -S damageproto
pacman -S db
pacman -S dbus
pacman -S dbus-glib
pacman -S dbus-sharp
pacman -S dbus-sharp-glib
pacman -S dconf
pacman -S dconf-editor
pacman -S deluge
pacman -S desktop-file-utils
pacman -S device-mapper
pacman -S dhclient
pacman -S dhcpcd
pacman -S dialog
pacman -S diffutils
pacman -S djvulibre
pacman -S dkms
pacman -S dnssec-anchors
pacman -S docker
pacman -S dosfstools
pacman -S dotconf
pacman -S e2fsprogs
pacman -S elfutils
pacman -S emacs
pacman -S empathy
pacman -S enca
pacman -S enchant
pacman -S eog
pacman -S epiphany
pacman -S espeak
pacman -S evince
pacman -S evolution-data-server
pacman -S exempi
pacman -S exiv2
pacman -S expat
pacman -S faac
pacman -S faad2
pacman -S fakeroot
pacman -S farstream
pacman -S ffmpeg
pacman -S fftw
pacman -S file
pacman -S file-roller
pacman -S filesystem
pacman -S findutils
pacman -S firefox
pacman -S fixesproto
pacman -S flac
pacman -S flex
pacman -S fluidsynth
pacman -S folks
pacman -S fontconfig
pacman -S fontforge
pacman -S fontsproto
pacman -S freecad
pacman -S freeglut
pacman -S freetype2
pacman -S fribidi
pacman -S ftgl
pacman -S fuse
pacman -S gawk
pacman -S gc
pacman -S gcc
pacman -S gcc-libs
pacman -S gconf
pacman -S gconf-sharp
pacman -S gcr
pacman -S gd
pacman -S gdal
pacman -S gdbm
pacman -S gdk-pixbuf2
pacman -S gdm
pacman -S gegl
pacman -S geoclue
pacman -S geoclue2
pacman -S geocode-glib
pacman -S geoip
pacman -S geoip-database
pacman -S geos
pacman -S gettext
pacman -S ghostscript
pacman -S giflib
pacman -S gimp
pacman -S git
pacman -S gjs
pacman -S glew
pacman -S glib-networking
pacman -S glib2
pacman -S glibc
pacman -S glibmm
pacman -S glu
pacman -S gmime
pacman -S gmp
pacman -S gnome-backgrounds
pacman -S gnome-bluetooth
pacman -S gnome-calculator
pacman -S gnome-color-manager
pacman -S gnome-contacts
pacman -S gnome-control-center
pacman -S gnome-desktop
pacman -S gnome-dictionary
pacman -S gnome-disk-utility
pacman -S gnome-font-viewer
pacman -S gnome-keyring
pacman -S gnome-menus
pacman -S gnome-online-accounts
pacman -S gnome-screenshot
pacman -S gnome-session
pacman -S gnome-settings-daemon
pacman -S gnome-shell
pacman -S gnome-shell-extensions
pacman -S gnome-system-log
pacman -S gnome-system-monitor
pacman -S gnome-terminal
pacman -S gnome-themes-standard
pacman -S gnome-tweak-tool
pacman -S gnome-user-docs
pacman -S gnome-user-share
pacman -S gnome-video-effects
pacman -S gnu-netcat
pacman -S gnupg
pacman -S gnustep-back
pacman -S gnustep-base
pacman -S gnustep-gui
pacman -S gnustep-make
pacman -S gnutls
pacman -S go
pacman -S gobject-introspection-runtime
pacman -S gom
pacman -S google-chrome
pacman -S gpgme
pacman -S gpm
pacman -S graphite
pacman -S grep
pacman -S grilo
pacman -S grilo-plugins
pacman -S gringo
pacman -S groff
pacman -S grub
pacman -S gsettings-desktop-schemas
pacman -S gsfonts
pacman -S gsm
pacman -S gst-plugins-bad
pacman -S gst-plugins-base
pacman -S gst-plugins-base-libs
pacman -S gst-plugins-good
pacman -S gstreamer
pacman -S gstreamer0.10
pacman -S gstreamer0.10-base
pacman -S gtk-sharp-2
pacman -S gtk-update-icon-cache
pacman -S gtk2
pacman -S gtk3
pacman -S gtkmm3
pacman -S gtksourceview3
pacman -S gtkspell
pacman -S guake
pacman -S gucharmap
pacman -S guile
pacman -S gvfs
pacman -S gvim
pacman -S gyp-git
pacman -S gzip
pacman -S hamster-time-tracker
pacman -S harfbuzz
pacman -S harfbuzz-icu
pacman -S hdf5
pacman -S hicolor-icon-theme
pacman -S hspell
pacman -S hub
pacman -S hunspell
pacman -S hunspell-en
pacman -S hunspell-ru
pacman -S hwids
pacman -S hwloc
pacman -S hyphen
pacman -S iana-etc
pacman -S icoutils
pacman -S icu
pacman -S ilmbase
pacman -S imagemagick
pacman -S imlib2
pacman -S inetutils
pacman -S inputproto
pacman -S intel-tbb
pacman -S iproute2
pacman -S iptables
pacman -S iputils
pacman -S iso-codes
pacman -S jack
pacman -S jansson
pacman -S jasper
pacman -S java-environment-common
pacman -S java-runtime-common
pacman -S jdk8-openjdk
pacman -S jemalloc
pacman -S jfsutils
pacman -S jre7-openjdk
pacman -S jre7-openjdk-headless
pacman -S jre8-openjdk
pacman -S jre8-openjdk-headless
pacman -S js
pacman -S js17
pacman -S json-c
pacman -S json-glib
pacman -S jsoncpp
pacman -S kbd
pacman -S kbproto
pacman -S keepass
pacman -S keyutils
pacman -S kmod
pacman -S krb5
pacman -S lame
pacman -S lapack
pacman -S lcms
pacman -S lcms2
pacman -S ldb
pacman -S ldns
pacman -S less
pacman -S lesstif
pacman -S lib32-acl
pacman -S lib32-alsa-lib
pacman -S lib32-attr
pacman -S lib32-bzip2
pacman -S lib32-curl
pacman -S lib32-e2fsprogs
pacman -S lib32-expat
pacman -S lib32-flac
pacman -S lib32-fontconfig
pacman -S lib32-freetype2
pacman -S lib32-gcc-libs
pacman -S lib32-gettext
pacman -S lib32-glib2
pacman -S lib32-glibc
pacman -S lib32-glu
pacman -S lib32-harfbuzz
pacman -S lib32-icu
pacman -S lib32-json-c
pacman -S lib32-keyutils
pacman -S lib32-krb5
pacman -S lib32-lcms2
pacman -S lib32-libasyncns
pacman -S lib32-libcap
pacman -S lib32-libdbus
pacman -S lib32-libffi
pacman -S lib32-libgcrypt
pacman -S lib32-libgpg-error
pacman -S lib32-libice
pacman -S lib32-libidn
pacman -S lib32-libjpeg-turbo
pacman -S lib32-libldap
pacman -S lib32-libmng
pacman -S lib32-libnl
pacman -S lib32-libogg
pacman -S lib32-libpcap
pacman -S lib32-libpng
pacman -S lib32-libpulse
pacman -S lib32-libsm
pacman -S lib32-libsndfile
pacman -S lib32-libssh2
pacman -S lib32-libtiff
pacman -S lib32-libusb
pacman -S lib32-libvorbis
pacman -S lib32-libx11
pacman -S lib32-libxau
pacman -S lib32-libxcb
pacman -S lib32-libxcursor
pacman -S lib32-libxdamage
pacman -S lib32-libxdmcp
pacman -S lib32-libxext
pacman -S lib32-libxfixes
pacman -S lib32-libxi
pacman -S lib32-libxrandr
pacman -S lib32-libxrender
pacman -S lib32-libxss
pacman -S lib32-libxtst
pacman -S lib32-libxv
pacman -S lib32-nvidia-libgl
pacman -S lib32-nvidia-utils
pacman -S lib32-openssl
pacman -S lib32-pcre
pacman -S lib32-qt4
pacman -S lib32-sqlite
pacman -S lib32-systemd
pacman -S lib32-util-linux
pacman -S lib32-v4l-utils
pacman -S lib32-xz
pacman -S lib32-zlib
pacman -S libabw
pacman -S libaio
pacman -S libao
pacman -S libarchive
pacman -S libass
pacman -S libassuan
pacman -S libasyncns
pacman -S libatasmart
pacman -S libatomic_ops
pacman -S libavc1394
pacman -S libbluray
pacman -S libbsd
pacman -S libcaca
pacman -S libcanberra
pacman -S libcanberra-pulse
pacman -S libcap
pacman -S libcap-ng
pacman -S libcddb
pacman -S libcdio
pacman -S libcdio-paranoia
pacman -S libcdr
pacman -S libchamplain
pacman -S libcroco
pacman -S libcue
pacman -S libcups
pacman -S libdaemon
pacman -S libdatrie
pacman -S libdbus
pacman -S libdca
pacman -S libdmapsharing
pacman -S libdrm
pacman -S libdv
pacman -S libdvdnav
pacman -S libdvdread
pacman -S libe-book
pacman -S libedit
pacman -S libepoxy
pacman -S libetonyek
pacman -S libev
pacman -S libevdev
pacman -S libevent
pacman -S libexif
pacman -S libffi
pacman -S libfontenc
pacman -S libfreexl
pacman -S libgcrypt
pacman -S libgcrypt15
pacman -S libgdata
pacman -S libgdiplus
pacman -S libgdm
pacman -S libgee
pacman -S libgeotiff
pacman -S libglade
pacman -S libgme
pacman -S libgnome-keyring
pacman -S libgnomekbd
pacman -S libgpg-error
pacman -S libgsf
pacman -S libgtop
pacman -S libgudev
pacman -S libgusb
pacman -S libgweather
pacman -S libgxps
pacman -S libibus
pacman -S libical
pacman -S libice
pacman -S libid3tag
pacman -S libidn
pacman -S libiec61883
pacman -S libimobiledevice
pacman -S libinput
pacman -S libiptcdata
pacman -S libjpeg-turbo
pacman -S libkeybinder2
pacman -S libksba
pacman -S libldap
pacman -S liblqr
pacman -S libmariadbclient
pacman -S libmbim
pacman -S libmediaart
pacman -S libmikmod
pacman -S libmm-glib
pacman -S libmms
pacman -S libmng
pacman -S libmodplug
pacman -S libmp4v2
pacman -S libmpc
pacman -S libmspub
pacman -S libmusicbrainz5
pacman -S libmwaw
pacman -S libnautilus-extension
pacman -S libndp
pacman -S libnewt
pacman -S libnice
pacman -S libnl
pacman -S libnm-glib
pacman -S libnotify
pacman -S liboauth
pacman -S libodfgen
pacman -S libofa
pacman -S libogg
pacman -S libomxil-bellagio
pacman -S libosinfo
pacman -S libotf
pacman -S libpagemaker
pacman -S libpaper
pacman -S libpcap
pacman -S libpciaccess
pacman -S libpeas
pacman -S libpgm
pacman -S libpipeline
pacman -S libplist
pacman -S libpng
pacman -S libpng12
pacman -S libproxy
pacman -S libpulse
pacman -S libpwquality
pacman -S libqmi
pacman -S libquvi
pacman -S libquvi-scripts
pacman -S libraw1394
pacman -S libreoffice-fresh
pacman -S librevenge
pacman -S librsvg
pacman -S libsamplerate
pacman -S libsasl
pacman -S libseccomp
pacman -S libsecret
pacman -S libshout
pacman -S libsigc++
pacman -S libsm
pacman -S libsndfile
pacman -S libsodium
pacman -S libsoup
pacman -S libspatialite
pacman -S libspectre
pacman -S libspiro
pacman -S libspnav
pacman -S libsrtp
pacman -S libssh
pacman -S libssh2
pacman -S libsystemd
pacman -S libtasn1
pacman -S libteam
pacman -S libtermkey-bzr
pacman -S libthai
pacman -S libtheora
pacman -S libtiff
pacman -S libtirpc
pacman -S libtool
pacman -S libtorrent-rasterbar
pacman -S libtracker-sparql
pacman -S libtxc_dxtn
pacman -S libudev.so.0
pacman -S libunicodenames
pacman -S libunistring
pacman -S libunwind
pacman -S libusb
pacman -S libusbmuxd
pacman -S libutempter
pacman -S libutil-linux
pacman -S libuv
pacman -S libva
pacman -S libvdpau
pacman -S libvisio
pacman -S libvisual
pacman -S libvorbis
pacman -S libvpx
pacman -S libvterm-git-neovim
pacman -S libwacom
pacman -S libwbclient
pacman -S libwebp
pacman -S libwmf
pacman -S libwnck
pacman -S libwnck3
pacman -S libwpd
pacman -S libwpg
pacman -S libx11
pacman -S libx264
pacman -S libxau
pacman -S libxaw
pacman -S libxcb
pacman -S libxcomposite
pacman -S libxcursor
pacman -S libxdamage
pacman -S libxdmcp
pacman -S libxext
pacman -S libxfixes
pacman -S libxfont
pacman -S libxft
pacman -S libxi
pacman -S libxinerama
pacman -S libxkbcommon
pacman -S libxkbcommon-x11
pacman -S libxkbfile
pacman -S libxkbui
pacman -S libxklavier
pacman -S libxml2
pacman -S libxmu
pacman -S libxp
pacman -S libxpm
pacman -S libxrandr
pacman -S libxrender
pacman -S libxres
pacman -S libxshmfence
pacman -S libxslt
pacman -S libxss
pacman -S libxt
pacman -S libxtst
pacman -S libxv
pacman -S libxxf86vm
pacman -S libyaml
pacman -S libzip
pacman -S licenses
pacman -S linux
pacman -S linux-api-headers
pacman -S linux-firmware
pacman -S linux-headers
pacman -S llvm-libs
pacman -S logrotate
pacman -S lpsolve
pacman -S lua
pacman -S lua-expat
pacman -S lua-socket
pacman -S lua51
pacman -S lua51-lpeg
pacman -S lua51-messagepack
pacman -S lua52
pacman -S lua52-bitop
pacman -S lua52-expat
pacman -S lua52-lpeg
pacman -S lua52-luajson
pacman -S lua52-socket
pacman -S luajit
pacman -S lvm2
pacman -S lz4
pacman -S lzo
pacman -S m17n-db
pacman -S m17n-lib
pacman -S m4
pacman -S make
pacman -S man-db
pacman -S man-pages
pacman -S mariadb
pacman -S mariadb-clients
pacman -S mc
pacman -S mcpp
pacman -S mdadm
pacman -S mesa
pacman -S mesa-demos
pacman -S mime-types
pacman -S mjpegtools
pacman -S mkinitcpio
pacman -S mkinitcpio-busybox
pacman -S mobile-broadband-provider-info
pacman -S mod_dnssd
pacman -S modem-manager-gui
pacman -S modemmanager
pacman -S mono
pacman -S mono-addins
pacman -S mousetweaks
pacman -S mozilla-common
pacman -S mpfr
pacman -S mpg123
pacman -S msgpack-c
pacman -S mtdev
pacman -S mutter
pacman -S nano
pacman -S nautilus
pacman -S nautilus-sendto
pacman -S ncurses
pacman -S neon
pacman -S neovim-git
pacman -S net-tools
pacman -S netbeans
pacman -S netcdf
pacman -S netctl
pacman -S nettle
pacman -S network-manager-applet
pacman -S networkmanager
pacman -S nixnote
pacman -S nm-connection-editor
pacman -S nodejs
pacman -S npm
pacman -S npth
pacman -S nspr
pacman -S nss
pacman -S ntfs-3g
pacman -S nvidia
pacman -S nvidia-libgl
pacman -S nvidia-utils
pacman -S ocaml
pacman -S ocaml-biniou
pacman -S ocaml-curl
pacman -S ocaml-easy-format
pacman -S ocaml-extlib
pacman -S ocaml-findlib
pacman -S ocaml-lwt
pacman -S ocaml-ounit
pacman -S ocaml-react
pacman -S ocaml-ssl
pacman -S ocaml-xmlm
pacman -S ocaml-yojson
pacman -S ocl-icd
pacman -S oolite
pacman -S opam
pacman -S openal
pacman -S opencascade
pacman -S opencollada
pacman -S opencolorio
pacman -S opencore-amr
pacman -S openexr
pacman -S openimageio
pacman -S openjpeg
pacman -S openmpi
pacman -S openresolv
pacman -S openshadinglanguage
pacman -S openssh
pacman -S openssl
pacman -S opus
pacman -S opusfile
pacman -S orc
pacman -S p11-kit
pacman -S p7zip
pacman -S package-query
pacman -S pacman
pacman -S pacman-mirrorlist
pacman -S pam
pacman -S pambase
pacman -S pango
pacman -S pangomm
pacman -S parted
pacman -S patch
pacman -S pciutils
pacman -S pcmciautils
pacman -S pcre
pacman -S perl
pacman -S perl-encode-locale
pacman -S perl-error
pacman -S perl-file-listing
pacman -S perl-file-next
pacman -S perl-html-parser
pacman -S perl-html-tagset
pacman -S perl-http-cookies
pacman -S perl-http-daemon
pacman -S perl-http-date
pacman -S perl-http-message
pacman -S perl-http-negotiate
pacman -S perl-libwww
pacman -S perl-lwp-mediatypes
pacman -S perl-net-http
pacman -S perl-uri
pacman -S perl-www-robotrules
pacman -S php
pacman -S php-intl
pacman -S php-sqlite
pacman -S pinentry
pacman -S pixman
pacman -S pkg-config
pacman -S playonlinux
pacman -S polkit
pacman -S poppler
pacman -S poppler-glib
pacman -S popt
pacman -S portaudio
pacman -S postgresql-libs
pacman -S ppp
pacman -S printproto
pacman -S procps-ng
pacman -S proj
pacman -S psmisc
pacman -S pth
pacman -S pulseaudio
pacman -S pulseaudio-alsa
pacman -S pygobject-devel
pacman -S pygobject2-devel
pacman -S pygtk
pacman -S pyqt5-common
pacman -S pyside-tools-common
pacman -S python
pacman -S python-dbus-common
pacman -S python-gobject
pacman -S python-pip
pacman -S python-pyside-common
pacman -S python-requests
pacman -S python-setuptools
pacman -S python-xdg
pacman -S python2
pacman -S python2-atspi
pacman -S python2-cairo
pacman -S python2-cffi
pacman -S python2-chardet
pacman -S python2-crypto
pacman -S python2-cryptography
pacman -S python2-dateutil
pacman -S python2-dbus
pacman -S python2-ecdsa
pacman -S python2-enum34
pacman -S python2-gconf
pacman -S python2-gobject
pacman -S python2-gobject2
pacman -S python2-idna
pacman -S python2-ipaddress
pacman -S python2-jinja
pacman -S python2-keybinder2
pacman -S python2-markupsafe
pacman -S python2-matplotlib
pacman -S python2-notify
pacman -S python2-numpy
pacman -S python2-paramiko
pacman -S python2-pivy
pacman -S python2-ply
pacman -S python2-pyasn1
pacman -S python2-pycparser
pacman -S python2-pyopenssl
pacman -S python2-pyparsing
pacman -S python2-pyqt5
pacman -S python2-pyside
pacman -S python2-pyside-tools
pacman -S python2-pytz
pacman -S python2-setuptools
pacman -S python2-shiboken
pacman -S python2-sip
pacman -S python2-six
pacman -S python2-twisted
pacman -S python2-wnck
pacman -S python2-xdg
pacman -S python2-yaml
pacman -S python2-zope-interface
pacman -S qt4
pacman -S qt5-base
pacman -S qt5-declarative
pacman -S qt5-location
pacman -S qt5-sensors
pacman -S qt5-webchannel
pacman -S qt5-webkit
pacman -S qt5-xmlpatterns
pacman -S qtchooser
pacman -S qtwebkit
pacman -S randrproto
pacman -S raptor
pacman -S rasqal
pacman -S re2c
pacman -S readline
pacman -S recode
pacman -S recordproto
pacman -S redland
pacman -S reiserfsprogs
pacman -S renderproto
pacman -S rescuetime
pacman -S rest
pacman -S rpmextract
pacman -S rsync
pacman -S rtkit
pacman -S rtmpdump
pacman -S ruby
pacman -S run-parts
pacman -S s-nail
pacman -S sbc
pacman -S schroedinger
pacman -S scons
pacman -S scrnsaverproto
pacman -S sdl
pacman -S sdl_mixer
pacman -S sed
pacman -S shadow
pacman -S shared-color-targets
pacman -S shared-mime-info
pacman -S shiboken
pacman -S sip
pacman -S skype
pacman -S slang
pacman -S smbclient
pacman -S smpeg
pacman -S snappy
pacman -S soqt
pacman -S sound-theme-freedesktop
pacman -S soundtouch
pacman -S spandsp
pacman -S speech-dispatcher
pacman -S speex
pacman -S speexdsp
pacman -S sqlite
pacman -S startup-notification
pacman -S steam
pacman -S sublime-text-dev
pacman -S sudo
pacman -S sushi
pacman -S sysfsutils
pacman -S systemd
pacman -S systemd-sysvcompat
pacman -S t1lib
pacman -S taglib
pacman -S talloc
pacman -S tar
pacman -S task
pacman -S tcl
pacman -S tdb
pacman -S telegram-desktop
pacman -S telepathy-farstream
pacman -S telepathy-glib
pacman -S telepathy-logger
pacman -S telepathy-mission-control
pacman -S tevent
pacman -S texinfo
pacman -S thin-provisioning-tools
pacman -S tk
pacman -S tmux
pacman -S tomboy
pacman -S totem
pacman -S totem-plparser
pacman -S tracker
pacman -S transmission-gtk
pacman -S ttf-dejavu
pacman -S tzdata
pacman -S udisks2
pacman -S uget
pacman -S unibilium
pacman -S unixodbc
pacman -S unrar
pacman -S unzip
pacman -S upower
pacman -S usb_modeswitch
pacman -S usbutils
pacman -S util-linux
pacman -S v4l-utils
pacman -S vi
pacman -S videoproto
pacman -S vifm
pacman -S vim-runtime
pacman -S vino
pacman -S virtualbox
pacman -S virtualbox-host-dkms
pacman -S virtualbox-host-modules
pacman -S vivaldi-snapshot
pacman -S vte
pacman -S vte-common
pacman -S vte3
pacman -S vtk
pacman -S wavpack
pacman -S wayland
pacman -S webkit2gtk
pacman -S webkitgtk
pacman -S webrtc-audio-processing
pacman -S wget
pacman -S which
pacman -S wildmidi
pacman -S wine
pacman -S winetricks
pacman -S wireless_tools
pacman -S wpa_supplicant
pacman -S wvdial
pacman -S wvstreams
pacman -S wxgtk
pacman -S wxpython
pacman -S x11-ssh-askpass
pacman -S x265
pacman -S xapian-core
pacman -S xbitmaps
pacman -S xcb-proto
pacman -S xcb-util
pacman -S xcb-util-image
pacman -S xcb-util-keysyms
pacman -S xcb-util-wm
pacman -S xclip
pacman -S xdebug
pacman -S xdg-user-dirs
pacman -S xdg-user-dirs-gtk
pacman -S xdg-utils
pacman -S xerces-c
pacman -S xextproto
pacman -S xf86-input-evdev
pacman -S xf86-input-mouse
pacman -S xf86vidmodeproto
pacman -S xfsprogs
pacman -S xineramaproto
pacman -S xkeyboard-config
pacman -S xmind
pacman -S xorg-bdftopcf
pacman -S xorg-font-util
pacman -S xorg-font-utils
pacman -S xorg-fonts-alias
pacman -S xorg-fonts-encodings
pacman -S xorg-fonts-misc
pacman -S xorg-luit
pacman -S xorg-mkfontdir
pacman -S xorg-mkfontscale
pacman -S xorg-server
pacman -S xorg-server-common
pacman -S xorg-server-xwayland
pacman -S xorg-setxkbmap
pacman -S xorg-xauth
pacman -S xorg-xhost
pacman -S xorg-xinit
pacman -S xorg-xkbcomp
pacman -S xorg-xmessage
pacman -S xorg-xprop
pacman -S xorg-xrdb
pacman -S xorg-xset
pacman -S xpad
pacman -S xplc
pacman -S xprintidle
pacman -S xproto
pacman -S xterm
pacman -S xvidcore
pacman -S xz
pacman -S yajl
pacman -S yaourt
pacman -S yelp
pacman -S yelp-xsl
pacman -S zeal
pacman -S zeitgeist
pacman -S zenity
pacman -S zeromq
pacman -S zip
pacman -S zita-alsa-pcmi
pacman -S zita-resampler
pacman -S zlib
pacman -S zsh
