source ~/src/dot/vim/vunble.vim
source ~/src/dot/vim/core.vim
source ~/src/dot/vim/gui.vim
source ~/src/dot/vim/indentation.vim
source ~/src/dot/vim/search.vim
source ~/src/dot/vim/filetypes.vim
"source ~/src/dot/vim/autoreload_vim.vim  " This not work with source
source ~/src/dot/vim/nerdtree.vim
source ~/src/dot/vim/experiments.vim
"source ~/src/dot/vim/neocomplite.vim
source ~/src/dot/vim/phpcomplite.vim
source ~/src/dot/vim/syntastic.vim
source ~/src/dot/vim/airline.vim
"source ~/src/dot/vim/ctrlp.vim
source ~/src/dot/vim/youcompliteme.vim
source ~/src/dot/vim/ultisnips.vim
source ~/src/dot/vim/unite.vim
source ~/src/dot/vim/auto-pairs.vim
source ~/src/dot/vim/php-namspace.vim
